name: Deploy Demo
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Build demo
        run: yarn run build:demo

      - name: Deploy demo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/demo
          git-config-name: GitHub Actions
          git-config-email: <>
